In [1]:
import pandas as pd
import numpy as  np
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Products.csv')
df

      Product  Price
0      Laptop  55000
1      Mobile  25000
2  Headphones   3000
3  Smartwatch   7000
4    Keyboard   1500
5       Mouse    800

In [3]:
average_price = np.mean(df['Price'])
print("average price =",average_price)

average price = 15383.333333333334

In [12]:
def above_average(data,avg):
  print("Products Price above average:")
  for i in range(len(data)):
    if data["Price"][i]>avg:
      print(data["Product"][i],"-",data["Price"][i])
above_average(df,average_price)

Products Price above average:
Laptop - 55000
Mobile - 25000

In [13]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/day,temperature.csv')
df

         day  temperature
0     Monday           18
1    Tuesday           24
2  Wednesday           35
3   Thursday           29
4     Friday           15
5   Saturday           32
6     Sunday           27

In [14]:
print(df)

         day  temperature
0     Monday           18
1    Tuesday           24
2  Wednesday           35
3   Thursday           29
4     Friday           15
5   Saturday           32
6     Sunday           27

In [15]:
highest = np.max(df['temperature'])
lowest = np.min(df['temperature'])
average = np.mean(df['temperature'])
print("highest temperature =",highest)
print('lowest temperature=',lowest)
print('average temperature=',average)

highest temperature = 35
lowest temperature= 15
average temperature= 25.714285714285715

In [18]:
def classify(temp):
  if temp < 20:
    return "cold"
  elif temp <=30:
    return "moderate"
  else:
    return "hot"

for i in range(len(df)):
  day = df['day'][i]
  temp = df['temperature'][i]
  category = classify(temp)
  print(day, "-", temp, "-", category)

Monday - 18 - cold
Tuesday - 24 - moderate
Wednesday - 35 - hot
Thursday - 29 - moderate
Friday - 15 - cold
Saturday - 32 - hot
Sunday - 27 - moderate

In [17]:
33
333